name: Java CI with Maven webdav

on:
  push:
    branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.Java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true

      - name: Upload jar to WebDAV
        env:
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASS: ${{ secrets.WEBDAV_PASS }}
        run: |
          FILE_NAME="yudao-server.jar"
          TARGET_URL="https://alist.335356119.xyz/dav/群晖/home/download/yudao/${FILE_NAME}"
          echo "Deleting old file (if exists) from WebDAV: ${TARGET_URL}"
          curl -X DELETE --fail -u "$WEBDAV_USER:$WEBDAV_PASS" "${TARGET_URL}" || echo "No old file found or deletion failed"
          echo "Uploading new file to WebDAV: ${TARGET_URL}"
          curl --progress-bar -T "yudao-server/target/${FILE_NAME}" -u "$WEBDAV_USER:$WEBDAV_PASS" "${TARGET_URL}"
